# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_version\test_gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(415, 326)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 40, 311, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_hoop_forwards = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_hoop_forwards.setObjectName("pb_hoop_forwards")
        self.gridLayout.addWidget(self.pb_hoop_forwards, 1, 0, 1, 1)
        self.pb_initialization = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_initialization.setObjectName("pb_initialization")
        self.gridLayout.addWidget(self.pb_initialization, 0, 0, 1, 1)
        self.pb_helical_forwards = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_helical_forwards.setObjectName("pb_helical_forwards")
        self.gridLayout.addWidget(self.pb_helical_forwards, 2, 0, 1, 1)
        self.pb_calculations = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_calculations.setObjectName("pb_calculations")
        self.gridLayout.addWidget(self.pb_calculations, 0, 1, 1, 1)
        self.pb_hoop_backwards = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_hoop_backwards.setObjectName("pb_hoop_backwards")
        self.gridLayout.addWidget(self.pb_hoop_backwards, 1, 1, 1, 1)
        self.pb_helical_backwards = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_helical_backwards.setObjectName("pb_helical_backwards")
        self.gridLayout.addWidget(self.pb_helical_backwards, 2, 1, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.pb_hoop_forwards.setText(_translate("main_window", "Hoop Forwards"))
        self.pb_initialization.setText(_translate("main_window", "Initialization"))
        self.pb_helical_forwards.setText(_translate("main_window", "Helical Forwards"))
        self.pb_calculations.setText(_translate("main_window", "Calculations"))
        self.pb_hoop_backwards.setText(_translate("main_window", "Hoop Backwards"))
        self.pb_helical_backwards.setText(_translate("main_window", "Helical Backwards"))


if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    '''ui = Ui_main_window()
    ui.setupUi(QtWidgets.QMainWindow())
    QtWidgets.QMainWindow().show()'''
    sys.exit(app.exec_())
